### ISSUE TITLE
python ceersdownload.py all: Max retries exceeded with url

### ISSUE THREAD

**Issue by xnaxe29** [ceers/ceers-nircam#1]
Dear Team,

While running 'python ceersdownload.py all' the total list contains 1936 rows. Although, I could only download 1215 files before i got this error - 

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mast.stsci.edu', port=443): Max retries exceeded with url: /api/v0.1/Download/file?uri=mast:JWST/product/jw01345061001_03201_00001_nrca2_uncal.fits (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x180ffc670>: Failed to establish a new connection: [Errno 51] Network is unreachable'))

The error is on the line 74 - 
manifest = Observations.download_products(files, #flat=True,...

Here is the total error description - 
Traceback (most recent call last):
  File "/Users/adarshranjan/Desktop/main_projects/asiaa_projects/submm_galaxies_project/JWST/my_codes/ceers-nircam-main_github/ceersdownload.py", line 119, in <module>
    main()
  File "/Users/adarshranjan/Desktop/main_projects/asiaa_projects/submm_galaxies_project/JWST/my_codes/ceers-nircam-main_github/ceersdownload.py", line 114, in main
    download_ceers(args.pointing, cleanup=args.cleanup, 
  File "/Users/adarshranjan/Desktop/main_projects/asiaa_projects/submm_galaxies_project/JWST/my_codes/ceers-nircam-main_github/ceersdownload.py", line 74, in download_ceers
    manifest = Observations.download_products(files, #flat=True, 
  File "/Users/adarshranjan/opt/anaconda3/envs/ceers/lib/python3.9/site-packages/astroquery/mast/observations.py", line 734, in download_products
    manifest = self._download_files(products,
  File "/Users/adarshranjan/opt/anaconda3/envs/ceers/lib/python3.9/site-packages/astroquery/mast/observations.py", line 617, in _download_files
    status, msg, url = self.download_file(data_product["dataURI"], local_path=local_path,
  File "/Users/adarshranjan/opt/anaconda3/envs/ceers/lib/python3.9/site-packages/astroquery/mast/observations.py", line 568, in download_file
    self._download_file(data_url, local_path,
  File "/Users/adarshranjan/opt/anaconda3/envs/ceers/lib/python3.9/site-packages/astroquery/query.py", line 351, in _download_file
    response = self._session.request("HEAD", url,
  File "/Users/adarshranjan/opt/anaconda3/envs/ceers/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/adarshranjan/opt/anaconda3/envs/ceers/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/adarshranjan/opt/anaconda3/envs/ceers/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mast.stsci.edu', port=443): Max retries exceeded with url: /api/v0.1/Download/file?uri=mast:JWST/product/jw01345061001_03201_00001_nrca2_uncal.fits (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x180ffc670>: Failed to establish a new connection: [Errno 51] Network is unreachable'))

Please let me know how to resolve this error and download all the CEERS files for reduction.

Thanks
Adarsh

**Comment by micaelabagley** [comment]
Hi Adarsh,

I think this error may have been related to a server issue on MAST, perhaps like what was reported in [this astroquery issue](https://github.com/astropy/astroquery/issues/2180).

Since you got pretty far in the download (1215/1936), you may consider rerunning <ceersdownload.py> and specify just the fields you're missing. 

Alternatively, the TEMPLATES team has provided a script for downloading JWST data that won't time out. It generates a bash script of curl commands that you can run to download the data, instead of staying connected to the MAST API.
Their script is available and documented [here](https://github.com/JWST-Templates/Notebooks)
